"""scenario ownership, skill packs, mcp servers

Revision ID: 06e68300418b
Revises: 4aa2aa57b4ea
Create Date: 2026-06-07 06:33:07.730315

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06e68300418b'
down_revision: str | Sequence[str] | None = '4aa2aa57b4ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(), server_default='general', nullable=False),
    sa.Column('transport', sa.String(), server_default='sse', nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), server_default='unknown', nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_servers_agent_id'), 'mcp_servers', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mcp_servers_category'), 'mcp_servers', ['category'], unique=False)
    op.create_index(op.f('ix_mcp_servers_is_public'), 'mcp_servers', ['is_public'], unique=False)
    op.create_index(op.f('ix_mcp_servers_owner_id'), 'mcp_servers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_mcp_servers_status'), 'mcp_servers', ['status'], unique=False)
    op.add_column('scenarios', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.add_column('scenarios', sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_scenarios_is_public'), 'scenarios', ['is_public'], unique=False)
    op.create_index(op.f('ix_scenarios_owner_id'), 'scenarios', ['owner_id'], unique=False)
    op.create_foreign_key(
        'fk_scenarios_owner_id_users', 'scenarios', 'users', ['owner_id'], ['id'], ondelete='CASCADE'
    )
    op.add_column('skills', sa.Column('skill_md', sa.Text(), server_default='', nullable=False))
    op.add_column('skills', sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('skills', sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'resources')
    op.drop_column('skills', 'manifest')
    op.drop_column('skills', 'skill_md')
    op.drop_constraint('fk_scenarios_owner_id_users', 'scenarios', type_='foreignkey')
    op.drop_index(op.f('ix_scenarios_owner_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_is_public'), table_name='scenarios')
    op.drop_column('scenarios', 'is_public')
    op.drop_column('scenarios', 'owner_id')
    op.drop_index(op.f('ix_mcp_servers_status'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_owner_id'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_is_public'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_category'), table_name='mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_agent_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
