"""refactor models: trips, inbox, relationships, skills v2, marketplace v2

Revision ID: 4aa2aa57b4ea
Revises: 92740f62549b
Create Date: 2026-06-07 02:15:57.435059

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aa2aa57b4ea'
down_revision: str | Sequence[str] | None = '92740f62549b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('marketplace_likes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'user_id', name='uq_marketplace_like_item_user')
    )
    op.create_index(op.f('ix_marketplace_likes_item_id'), 'marketplace_likes', ['item_id'], unique=False)
    op.create_index(op.f('ix_marketplace_likes_user_id'), 'marketplace_likes', ['user_id'], unique=False)
    op.create_table('marketplace_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['marketplace_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version', name='uq_marketplace_version_item_version')
    )
    op.create_index(op.f('ix_marketplace_versions_item_id'), 'marketplace_versions', ['item_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('from_agent_id', sa.Uuid(), nullable=False),
    sa.Column('to_agent_id', sa.Uuid(), nullable=False),
    sa.Column('strength', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('encounters_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'from_agent_id', 'to_agent_id', name='uq_relationship_owner_from_to')
    )
    op.create_index(op.f('ix_relationships_from_agent_id'), 'relationships', ['from_agent_id'], unique=False)
    op.create_index(op.f('ix_relationships_owner_id'), 'relationships', ['owner_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_agent_id'), 'relationships', ['to_agent_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('task_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('agent_status', sa.String(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('summary_report_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_agent_id'), 'trips', ['agent_id'], unique=False)
    op.create_index(op.f('ix_trips_created_by'), 'trips', ['created_by'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_table('trip_encounters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_key', sa.String(), nullable=True),
    sa.Column('opponent_agent_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('postcard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opponent_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_encounters_trip_id'), 'trip_encounters', ['trip_id'], unique=False)
    op.add_column('agents', sa.Column('source_version', sa.Integer(), nullable=True))
    op.add_column('marketplace_items', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('marketplace_items', sa.Column('fork_mode', sa.String(), server_default='editable', nullable=False))
    op.add_column('marketplace_items', sa.Column('likes', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('marketplace_items', sa.Column('forks', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('marketplace_items', sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('marketplace_items', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketplace_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('reports', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('skills', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('skills', sa.Column('prompt_body', sa.Text(), server_default='', nullable=False))
    op.add_column('skills', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('skills', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('skills', sa.Column('executable', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('skills', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_skills_is_public'), 'skills', ['is_public'], unique=False)
    # ### end Alembic commands ###

    # Backfill the v1→v2 aliases so existing rows stay consistent: prompt_body
    # mirrors the legacy content, and forks mirrors the legacy downloads counter.
    op.execute("UPDATE skills SET prompt_body = content WHERE prompt_body = '' AND content <> ''")
    op.execute("UPDATE marketplace_items SET forks = downloads")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_is_public'), table_name='skills')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'is_public')
    op.drop_column('skills', 'executable')
    op.drop_column('skills', 'tags')
    op.drop_column('skills', 'params')
    op.drop_column('skills', 'prompt_body')
    op.drop_column('skills', 'description')
    op.alter_column('reports', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('marketplace_items', 'updated_at')
    op.drop_column('marketplace_items', 'snapshot')
    op.drop_column('marketplace_items', 'views')
    op.drop_column('marketplace_items', 'forks')
    op.drop_column('marketplace_items', 'likes')
    op.drop_column('marketplace_items', 'fork_mode')
    op.drop_column('marketplace_items', 'version')
    op.drop_column('agents', 'source_version')
    op.drop_index(op.f('ix_trip_encounters_trip_id'), table_name='trip_encounters')
    op.drop_table('trip_encounters')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_by'), table_name='trips')
    op.drop_index(op.f('ix_trips_agent_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_relationships_to_agent_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_owner_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_agent_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_marketplace_versions_item_id'), table_name='marketplace_versions')
    op.drop_table('marketplace_versions')
    op.drop_index(op.f('ix_marketplace_likes_user_id'), table_name='marketplace_likes')
    op.drop_index(op.f('ix_marketplace_likes_item_id'), table_name='marketplace_likes')
    op.drop_table('marketplace_likes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
