"""add agent prompt_config

Revision ID: 92740f62549b
Revises: 610db5a44c38
Create Date: 2026-06-07 01:28:22.699209

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92740f62549b'
down_revision: str | Sequence[str] | None = '610db5a44c38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Backfill existing rows with an empty object so the NOT NULL add is safe on a
    # populated table (the prompt builder treats {} as "fall back to legacy fields").
    op.add_column(
        'agents',
        sa.Column(
            'prompt_config',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'prompt_config')
    # ### end Alembic commands ###
